__all__ = ['FunctionBuilder']

from mcpack import Function

from . import __version__
from .resource import ResourceBuilder


class FunctionBuilder(ResourceBuilder):
    guard_name = 'function'

    def __init__(self, ctx, name, resource):
        super().__init__(ctx, name, resource)
        self.function_body = (f'# Generated by endermite v{__version__}\n'
                              '# Modifications will be overwritten\n\n')

    def build(self):
        self.function_body += '\n'.join(map(str, self.resource)) + '\n'

    def populate(self, pack):
        pack[self.name] = Function(self.function_body)
